name: pveiwer3d
version: 0.0.1
description: A starter template for a polymer.dart web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  ace_polymer: any
  browser: any
  paper_elements: '>=0.6.1 <0.7.0'
  polymer: '>=0.15.4 <0.16.0'
  uuid: any
  vector_math: any
transformers:
- polymer:
    entry_points: web/index.html
